title: Temer Golpista
tagline: Um plugin para navegadores que troca Michel Temer por Temer Golpista
fullurl: "https://hacktivismcwb.github.io/temergolpista/" #used for fb share content
fbsharetext: Um plugin para navegadores que troca Michel Temer por Temer Golpista. Disponivel para Chrome.
fbshareimg: http://hacktivismcwb.github.io/temergolpista/temer-golpista-fb-share.jpg
