title: Temer Golpista
tagline: Deixe seu navegador dizer a verdade com esse plugin que troca 'MicheI Temer' por 'Temer Golpista'.
fullurl: "http://temergolpista.greve.xyz/" #used for fb share content
fbsharetext: Deixe seu navegador dizer a verdade com esse plugin que troca 'MicheI Temer' por 'Temer Golpista'.
fbshareimg: http://temergolpista.greve.xyz/temer-golpista-fb-share.jpg
