title: Temer Golpista
tagline: Deixe seu navegador dizer a verdade com esse plugin que troca 'Michel Temer' por 'Temer Golpista'.
fullurl: "https://hacktivismcwb.github.io/temergolpista/" #used for fb share content
fbsharetext: Deixe seu navegador dizer a verdade com esse plugin que troca 'Michel Temer' por 'Temer Golpista'.
fbshareimg: http://hacktivismcwb.github.io/temergolpista/temer-golpista-fb-share.jpg
